import Head from "next/head";
import Image from "next/image";
import { Nav } from "../../components/nav";
import { Contact } from "../../components/homeComponents/contact";
import { Footer } from "../../components/homeComponents/footer";
import styles from "../../styles/Home.module.css";
import { ProjectPage } from "../../components/projectComponents/projectPage";

export default function Bluprint() {
  let images = [
    {
      url: "/projectCards/bluprint.png",
      caption:
        "A mockup of Bluprint being used on a tablet, showing a project's home dashboard.",
    },
    {
      url: "/branding/bluprint/bg.png",
      caption: "A cover photo for use on Youtube, Facebook and LinkedIn.",
    },
    {
      url: "/branding/bluprint/GIF.gif",
      caption:
        "A simulated animation showing various features of Bluprint being used.",
    },
    {
      url: "/branding/bluprint/logos.png",
      caption:
        "A little look at the website I designed and built for Wraptor Customs.",
    },
  ];

  function igLink(username) {
    router.push(`https://instagram.com/${username}`);
  }

  function webLink(url) {
    router.push(url);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>
          Bluprint - Robbidesigns | Branding, Social Media & Website Designer
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.svg" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins&family=Roboto:wght@400;500&display=swap"
          rel="stylesheet"
        ></link>
      </Head>

      <ProjectPage
        username={"bluprint.app"}
        url={"https://bluprint.uk"}
        images={images}
        title={"Bluprint"}
        desc={"Brand design, interface design and development of Bluprint."}
        about={[
          "Bluprint is a work-in-progress brand asset design and management tool that I'm currently developing under my company Quirk. Studios. The aim with Bluprint is to make brand asset creation and management simple for everyone, helping you design consistently and manage assets effectivily, reducing the need for expensive software or agencies.",
          "We initially set out in establishing our branding for Bluprint, as well as completing some user research through the entreprenuer platform Pioneer. This helped us identify the target market for our product, as well as the correct feature set to provide for launch. We opted for a rather simplistic visual style for Bluprint, taking inspiration from actual blueprints, scribbled notes, etc., which we saw as fitting given the platforms purpose.",
          "After we we're happy with the branding for Bluprint, I set off coming up with a suitable user interface for the initial feature set that we had in mind. Getting a rough idea for how Bluprint would look has helped us with creating some content ready for build hype for the product and has helped me visualise Bluprint whilst developing it. Bluprint is currently in development and we've got our eyes set on a Q1 2023 launch.",
        ]}
        guidelines={"/branding/bluprint/guidelines.pdf"}
      />
    </div>
  );
}
