import Head from "next/head";
import Image from "next/image";
import { Nav } from "../../components/nav";
import { Contact } from "../../components/homeComponents/contact";
import { Footer } from "../../components/homeComponents/footer";
import styles from "../../styles/Home.module.css";
import { ProjectPage } from "../../components/projectComponents/projectPage";

export default function Fiesta() {
  let images = [
    {
      url: "/branding/fiesta/fiesta.png",
    },
    {
      url: "/branding/fiesta/Group 204.png",
    },
    {
      url: "/branding/fiesta/brand.png",
    },
    {
      url: "/branding/fiesta/Clearspace.png",
    },
  ];

  function igLink(username) {
    router.push(`https://instagram.com/${username}`);
  }

  function webLink(url) {
    router.push(url);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>
          Fiesta - Robbidesigns | Branding, Social Media & Website Designer
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.svg" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins&family=Roboto:wght@400;500&display=swap"
          rel="stylesheet"
        ></link>
      </Head>

      <ProjectPage
        url={"/"}
        images={images}
        title={"Fiesta"}
        desc={"Small brand design and packaging design."}
        about={[
          "Under Quirk. Studios we we're asked to design some packaging and branding for a new flavoured water product. After speaking with the client, we agreed to go with for a cosy, handdrawn feel to their brand and packaging design. I found a series of patterned fruit drawings which the client loved - these patterns played a big role in the brands design. The name Fiesta helped me come up with a tagline for the brand, Halo Sabor, which translates from Spanish to Hello Flavour, which seemed fitting for the product type.",
          "I opted for a colour scheme featuring an off-white and off-black, as well as orangy-yellow and salmon red. The latter colours are in reference to the first two flavours, lemon & raspberry. ",
        ]}
        guidelines={"/"}
      />
    </div>
  );
}
