import Head from "next/head";
import Image from "next/image";
import { Hero } from "../../components/homeComponents/hero";
import { ResumeSection } from "../../components/homeComponents/resume";
import { Nav } from "../../components/nav";
import { Contact } from "../../components/homeComponents/contact";
import { Footer } from "../../components/homeComponents/footer";
import styles from "../../styles/Home.module.css";
import { ProjectViewerLG } from "../../components/homeComponents/projectViewerLG";

export default function ProjectsPage() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Robbidesigns | Branding, Social Media & Website Designer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.svg" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap"
          rel="stylesheet"
        ></link>
      </Head>

      <Nav />

      <ProjectViewerLG />

      <Contact />

      <Footer />
    </div>
  );
}
