import Head from "next/head";
import Image from "next/image";
import { Nav } from "../../components/nav";
import { Contact } from "../../components/homeComponents/contact";
import { Footer } from "../../components/homeComponents/footer";
import styles from "../../styles/Home.module.css";
import { ProjectPage } from "../../components/projectComponents/projectPage";

export default function JustAesthetics() {
  let images = [
    { url: "/branding/justaesthetics/justaesthetics.png" },
    { url: "/branding/justaesthetics/shoppage.png" },
    { url: "/branding/justaesthetics/Home.png" },
  ];

  return (
    <div className={styles.container}>
      <Head>
        <title>Robbidesigns | Branding, Social Media & Website Designer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.svg" />
      </Head>

      <Head>
        <title>
          JustAesthetics - Robbidesigns | Branding, Social Media & Website
          Designer
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.svg" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins&family=Roboto:wght@400;500&display=swap"
          rel="stylesheet"
        ></link>
      </Head>

      <ProjectPage
        username={"delticbusiness"}
        url={"https://delticbusiness.co.uk"}
        images={images}
        title={"JustAesthetics"}
        desc={"A website design for a skin care and aesthetics company."}
        about={[
          "I was asked to design a website for a local skin care and aesthetics company, JustAesthetics. The client expressed a desire for a website which was mostly monochrome, with the majority of the colour coming from imagery. Designing such a website was a challenging task for me.",
          "The website was to feature information regarding their treatments, as well as catelogue showing COSMED products that were available through JustAesthetics. I designed an e-commerce like experience without any of the ordering and payment features, but instead through to an email request form.",
        ]}
        guidelines={"/"}
      />
    </div>
  );
}
