import Head from "next/head";
import Image from "next/image";
import { Nav } from "../../components/nav";
import { Contact } from "../../components/homeComponents/contact";
import { Footer } from "../../components/homeComponents/footer";
import styles from "../../styles/Home.module.css";
import { ProjectPage } from "../../components/projectComponents/projectPage";

export default function QuirkStudios() {
  let images = [
    {
      url: "/branding/quirk/quirk.png",
    },
    {
      url: "/branding/quirk/designdonedifferently.png",
    },
    {
      url: "/branding/quirk/About_Us.png",
    },
    {
      url: "/branding/quirk/scribbles.png",
    },
  ];

  function igLink(username) {
    router.push(`https://instagram.com/${username}`);
  }

  function webLink(url) {
    router.push(url);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>
          Quirk. Studios - Robbidesigns | Branding, Social Media & Website
          Designer
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.svg" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins&family=Roboto:wght@400;500&display=swap"
          rel="stylesheet"
        ></link>
      </Head>

      <ProjectPage
        username={"wearequirk.studio"}
        url={"https://quirk.studio"}
        images={images}
        title={"Quirk. Studios"}
        desc={"New website design & logo design."}
        about={[
          "Quirk. Studio is a new brand design & content creation I've co-founded, which is currently in it's very early days, as part of the Priority¹ Studios Group,. We've been able to gain a few clients from our previous roles, so our initial focus was getting a logo together, some brand messaging, as well as a website. We will be properly looking at Quirk. Studios' brand design and messaging in the near future.",
          "With our clients we like to provide quirky/different solutions to the norm, so we knew that we had to stand out. We opted for the name Quirk, a beautiful vibrant shade of purple and the tagline 'Design. Done. Differently.' This currently forms the basis of our brand going forward, but we currently lack any more depth into our brand and its messaging. I designed a simplistic text-based logo and icon, using a colour scheme of two shades of purple, black and white.",
          "I've put together a small website together for Quirk, which allows us to outline the services we offer and the work that we've done. Our next focus is fully defining our brand, providing more depth to our website and creating engaging content for our social medias.",
        ]}
        guidelines={"/"}
      />
    </div>
  );
}
