import Head from "next/head";
import Image from "next/image";
import { Nav } from "../../components/nav";
import { Contact } from "../../components/homeComponents/contact";
import { Footer } from "../../components/homeComponents/footer";
import styles from "../../styles/Home.module.css";
import { ProjectPage } from "../../components/projectComponents/projectPage";

export default function WraptorCustoms() {
  let images = [
    {
      url: "/branding/wraptor/brand.png",
      caption:
        "Two pages from a small brand adjustments document, covering the changes in colour scheme and typography.",
    },
    {
      url: "/branding/wraptor/THEAPPLE-min.png",
      caption:
        "A graphic I created to help promote a project video. These have been used on Youtube, Facebook and Instagram.",
    },
    {
      url: "/branding/wraptor/subaru.png",
      caption:
        "A graphic I created to help promote a project video. These have been used on Youtube, Facebook and Instagram.",
    },
    {
      url: "/branding/wraptor/website.gif",
      caption:
        "A little look at the website I designed and built for Wraptor Customs.",
    },
  ];

  function igLink(username) {
    router.push(`https://instagram.com/${username}`);
  }

  function webLink(url) {
    router.push(url);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>
          Wraptor Customs - Robbidesigns | Branding, Social Media & Website
          Designer
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.svg" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins&family=Roboto:wght@400;500&display=swap"
          rel="stylesheet"
        ></link>
      </Head>

      <ProjectPage
        username={"wraptor_customs_tuning_wraps"}
        url={"https://wraptorcustoms.com"}
        fb={"https://www.facebook.com/wraptorWAG"}
        yt={"https://www.youtube.com/@wraptorcustoms"}
        tt={"https://tiktok.com/wraptorcustoms"}
        images={images}
        title={"Wraptor Customs"}
        desc={
          "A realignment of Wraptor Customs branding, bringing the website, social media and physical assets together visually, as well as video content creation for Instagram, Youtube and Tiktok."
        }
        about={[
          "Wraptor Customs' previous website and social media was going in a creative direction that the client wasn't happy with. There seemed to be a lack of cohesion between the digital brand elements, content, website and physical branding. I set out to create some colourful and playful branding, which helped their business stand out from the sea of stealthy and luxury branded car businesses. Since Wraptor started, the founder Dudley Ginn, has always been about breaking away from the norm and creating a business which is vibrant and a bit bonkers! After many conversions with the client, I agreed with the team that playing into the playful nature of the business across their branding was the best direction to go with.",
          "I decided to stick with some of the brand assets, such as the logo and video introduction, because I felt they aligned well with the visual direction we we're heading in, and helped keep within the clients budget constraints. As a result, a new colour scheme was decided - I went with a monochrome approach to the main brand colours, adding pops of colour through rainbow-esque accents. The colours used in the rainbow represented different services that Wraptor Customs offered. The fonts we're changed to help with readibility and a cartoon-style theme was set to provide consistency.",
          "Once we were set on the branding, we set out on designing a website and creation content, that both aligned with Wraptor's new brand guidelines (both of which I was the design lead on).",
        ]}
        guidelines={"/"}
      />
    </div>
  );
}
