import Head from "next/head";
import Image from "next/image";
import { Hero } from "../components/homeComponents/hero";
import { ResumeSection } from "../components/homeComponents/resume";
import { Nav } from "../components/nav";
import { Contact } from "../components/homeComponents/contact";
import { Footer } from "../components/homeComponents/footer";
import styles from "../styles/Home.module.css";
import { ProjectViewerLG } from "../components/homeComponents/projectViewerLG";

export default function ProjectsPage() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />

      <ProjectViewerLG />

      <Contact />

      <Footer />
    </div>
  );
}
